### ISSUE TITLE
Django runserver does not load when ipinfo middleware added in settings file

### ISSUE THREAD

**Issue by ManiBlitz** [ipinfo/django#3]
Hello, I am not sure if I am doing everything correctly but once I add the middleware definition for IPInfo in the ``settings.py`` file of my django project, I get the following error message.
```
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/Users/kevin_tiba/miniconda3/envs/django_env/lib/python3.7/site-packages/django/core/servers/basehttp.py", line 45, in get_internal_wsgi_application
    return import_string(app_path)
  File "/Users/kevin_tiba/miniconda3/envs/django_env/lib/python3.7/site-packages/django/utils/module_loading.py", line 17, in import_string
    module = import_module(module_path)
  File "/Users/kevin_tiba/miniconda3/envs/django_env/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/kevin_tiba/PycharmProjects/animals/animals/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/Users/kevin_tiba/miniconda3/envs/django_env/lib/python3.7/site-packages/django/core/wsgi.py", line 13, in get_wsgi_application
    return WSGIHandler()
  File "/Users/kevin_tiba/miniconda3/envs/django_env/lib/python3.7/site-packages/django/core/handlers/wsgi.py", line 135, in __init__
    self.load_middleware()
  File "/Users/kevin_tiba/miniconda3/envs/django_env/lib/python3.7/site-packages/django/core/handlers/base.py", line 35, in load_middleware
    middleware = import_string(middleware_path)
  File "/Users/kevin_tiba/miniconda3/envs/django_env/lib/python3.7/site-packages/django/utils/module_loading.py", line 17, in import_string
    module = import_module(module_path)
  File "/Users/kevin_tiba/miniconda3/envs/django_env/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/kevin_tiba/miniconda3/envs/django_env/lib/python3.7/site-packages/ipinfo_django/middleware.py", line 3, in <module>
    import ipinfo
  File "/Users/kevin_tiba/miniconda3/envs/django_env/lib/python3.7/site-packages/ipinfo/__init__.py", line 1, in <module>
    from .handler import Handler
  File "/Users/kevin_tiba/miniconda3/envs/django_env/lib/python3.7/site-packages/ipinfo/handler.py", line 10, in <module>
    from .cache.default import DefaultCache
  File "/Users/kevin_tiba/miniconda3/envs/django_env/lib/python3.7/site-packages/ipinfo/cache/default.py", line 6, in <module>
    from .interface import CacheInterface
  File "/Users/kevin_tiba/miniconda3/envs/django_env/lib/python3.7/site-packages/ipinfo/cache/interface.py", line 6, in <module>
    import six
ModuleNotFoundError: No module named 'six'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/kevin_tiba/miniconda3/envs/django_env/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/Users/kevin_tiba/miniconda3/envs/django_env/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/kevin_tiba/miniconda3/envs/django_env/lib/python3.7/site-packages/django/utils/autoreload.py", line 54, in wrapper
    fn(*args, **kwargs)
  File "/Users/kevin_tiba/miniconda3/envs/django_env/lib/python3.7/site-packages/django/core/management/commands/runserver.py", line 137, in inner_run
    handler = self.get_handler(*args, **options)
  File "/Users/kevin_tiba/miniconda3/envs/django_env/lib/python3.7/site-packages/django/contrib/staticfiles/management/commands/runserver.py", line 27, in get_handler
    handler = super().get_handler(*args, **options)
  File "/Users/kevin_tiba/miniconda3/envs/django_env/lib/python3.7/site-packages/django/core/management/commands/runserver.py", line 64, in get_handler
    return get_internal_wsgi_application()
  File "/Users/kevin_tiba/miniconda3/envs/django_env/lib/python3.7/site-packages/django/core/servers/basehttp.py", line 50, in get_internal_wsgi_application
    ) from err
django.core.exceptions.ImproperlyConfigured: WSGI application 'animals.wsgi.application' could not be loaded; Error importing module.
```

Here is the middleware section:
```
MIDDLEWARE = [
    'ipinfo_django.middleware.IPinfo',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
```

**Comment by UmanShahzad** [comment]
@ManiBlitz Try putting the middleware at the bottom of all the others.

**Comment by ManiBlitz** [comment]
Still the same result. I have checked all the elements in my django settings file and it is the only thing that seems to cause the error. Here is the complete ``settings.py``file. (I masked some values for security):

```
"""
Django settings for animals project.

Generated by 'django-admin startproject' using Django 2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '*****'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    '*****',
    '*****',
    '*****',
    '*****',
    '*****',
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'animals_server.apps.AnimalsServerConfig',
    'rest_framework',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'ipinfo_django.middleware.ipinfo',
]

ROOT_URLCONF = 'animals.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

IPINFO_TOKEN = '1905cd2b0ebeed'

WSGI_APPLICATION = 'animals.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': '*****',
        'NAME': '*****',
        'USER': '*****',
        'PASSWORD': '*****',
        'HOST': '*****',
        'PORT': '',
    }
}

REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10
}

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'

```

**Comment by ManiBlitz** [comment]
I solved the issue by importing the library six. Apparently, it solves issues of interdependencies between python 2.7 and python 3.7. Thanks for the help.

**Comment by UmanShahzad** [comment]
@ManiBlitz Cool, though I noticed it revealed another issue with the underlying Python library itself and what dependencies it stated it needed. I'll fix that, but glad you got your issue fixed.
